#!/bin/bash

version=1.0
echo -e "A999X Activator (A9X, iOS 9, 9 years later) v$version\n(C) 2025 Samuel Bowers (3-BSD)\

# Global vars.
os="$(uname)"
arch="$(uname -m)"
device=
ver=
serial=
not_normal=false
file=
# Used to check if we need iOS 16 to be restored to get activation files, it doubles as a disable to prevent a recursive infinite loop when calling the restore_ipsw() func as well.
restore_ios_16=false

# OS/arch detection.
# Add all the self-contained binaries we need to the $PATH used within this script.
real_portable_folder="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ "$os" = "Linux" ]; then

    if [ "$arch" = "x86_64" ]; then
        PATH="${PATH:+$PATH:}$real_portable_folder/bin/Legacy-iOS-Kit/bin/linux/x86_64:$real_portable_folder/bin/turdus_m3rula_1.1_b0ea3ee7_linux-amd64/bin"
    elif [ "$arch" = "arm64" ]; then
        PATH="${PATH:+$PATH:}$real_portable_folder/bin/Legacy-iOS-Kit/bin/linux/arm64:$real_portable_folder/bin/turdus_m3rula_1.1_b0ea3ee7_linux-arm64/bin"
    else
        echo "Error: Linux on $arch is not supported."
        exit 1
    fi

    echo "Detected Linux on $arch."

elif [[ "$os" == "Darwin" ]]; then
    PATH="${PATH:+$PATH:}$real_portable_folder/bin/Legacy-iOS-Kit/bin/macos:$real_portable_folder/bin/turdus_m3rula_1.1_b0ea3ee7_macos/bin"
    echo "Detected Mac OS on $arch."
else
    echo "Error: $os is not supported."
    exit 1
fi

cd "$real_portable_folder"
echo "PATH: $PATH"

# Trick lifted from https://docs.website-msw.pages.dev/docs/get-started/installing-palera1n-linux/.
usbmuxd_reset() {
    if [ "$os" == "Linux" ]; then
        systemctl stop usbmuxd > /dev/null 2>&1
        # If usbmuxd is still running kill it forcibly.
        killall -9 usbmuxd > /dev/null 2>&1
        usbmuxd -f -p &
    fi
}

# Note: this only does so much because it appears that if the  was in DFU Mode and then exited it will auto-boot=true...
enforce_recovery() {
    irecovery -c "setenv auto-boot false"
    irecovery -c "saveenv"
}

pair_iPad() {
    while ! idevicepair pair 2>/dev/null; do
        
        if [ "$tried_once" = "true" ]; then
            break;
        fi

        # Because we break above, never gets here on try 2.
        if [ "$1" = "first_time" ]; then
            echo "No iPad detected. It may not be paired to your computer if it is indeed in Normal Mode."
        fi

        read -p "If your iPad has a passcode, unlock your iPad and then tap trust if prompted. If your not being prompted, unplug the USB-A to Lightning cable from your Mac then plug it back in. Then presss enter."
        
        # The first time we call this is on program startup, and we don't even know if a device is connected so we don't want to get into a normal mode check loop if say user connects via Recovery or DFU mode device after we are already here.
        if [ "$1" = "first_time" ]; then
            tried_once=true
            echo "Checking one more time for iPad in Normal Mode to see if it has been paired..."
        fi
    done

    # Clean up
    tried_once=false
}

iproxy_start() {
    iproxy 6414 22 > /dev/null 2>&1 &
}

iproxy_kill() {
    killall iproxy > /dev/null 2>&1
}

did_you_follow_instructions() {
    pair_iPad
    read -p "* Activate the iPad. IMPORTANT: If you are going to use cellular features on iOS 9, your SIM card should be in the iPad with an active carrier. 

* Sign in to iCloud and complete Setup.app. Get to the home screen. 

* Make sure Find My iPad has been turned off.

After all of the above is true press any key to continue..."
    wait_for_activation
}

is_activated() {

    if ideviceinfo | grep -q "^ActivationState: Activated$"; then
        return 0
    else
        return 1
    fi
}

restore_ios_16_for_device() {
    if [ $device == "ipad-pro-12.9" ]; then
        restore_ipsw https://updates.cdn-apple.com/2025FallFCS/fullrestores/082-66297/26CFD5DD-0DB1-46E1-9B3E-78B3C5B922D1/iPadPro_12.9_16.7.12_20H364_Restore.ipsw
    elif [ $device == "ipad-pro-9.7" ]; then
        restore_ipsw https://updates.cdn-apple.com/2025FallFCS/fullrestores/082-66287/D653C09C-9C6D-4B88-AA9A-7FFB449DD9F5/iPadPro_9.7_16.7.12_20H364_Restore.ipsw
    fi
    
    # Clean up.
    restore_ios_16=false

    wait_for_normal_mode
    echo "iOS 16.7.12 has been restored! It will take some additional time for it to start up into Setup.app, please wait..."
 
    did_you_follow_instructions
}

boot_turdusra1n() {
    usbmuxd_reset
    wait_for_recovery

    # Can not trust return values of turdusra1n because at least my 256GB Pro 12.9 reboots to recovery very occasionally. This has never happened on my 32GB TSMC Pro 12.9". It appears to be an issue with turdus merula because it won't show as much output (never gets to bootx) but still returns 0.
    while irecovery -m 2>/dev/null | grep -q "Recovery Mode"; do
        usbmuxd_reset
        echo "Info: If you get an error about failed to open handle (no device) after Checkmate?, disconnect then reconnect your iPad."

        while ! turdusra1n -TP data/$device-$serial/$ver/block/*-pteblock2.bin; do
            usbmuxd_reset
            echo "Something went wrong, lets try that again."
        done

        # Give time to exit Recovery Mode so this is not executed again erronously.
        echo "Please wait, checking for proper booting in 20 seconds"
        sleep 20
    done

    wait_for_normal_mode
}

enter_recovery() {    
    if ! irecovery -m 2>/dev/null | grep -q "Recovery Mode"; then
        # If not in Recovery Mode assume in Normal Mode and attempt to enter Recovery Mode. If this fails we are already in Recovery Mode or possibly DFU Mode so we don't want to show an error."
        if ideviceenterrecovery "$(ideviceinfo -k UniqueDeviceID 2>/dev/null)" >/dev/null 2>&1; then
            # If this succeded lets tell the user what's going on. If it didn't succed then that's ok we don't need to tell them anything due to the above reasoning....
            echo "Entering Recovery Mode, please wait..."
        fi
        
        # If this was DFU Mode this is fine to show the user because it gets them back on track...
        wait_for_recovery
    fi
}

wait_for_normal_mode() {
    while ! ideviceinfo >/dev/null 2>&1; do
       # Ensure we are paired, fixes issues when booting iOS 9.
        idevicepair pair >/dev/null 2>&1
        echo "Waiting for iPad to boot..."
        sleep 1
    done
}

wait_for_recovery() {
     while ! irecovery -m 2>/dev/null | grep -q "Recovery Mode"; do
        if irecovery -m 2>/dev/null | grep -q "DFU Mode"; then
            echo "DFU Mode detected. Please press the HOME+POWER buttons until your iPad reboots into Recovery Mode. Do not stop pressing those buttons until you get to Recovery Mode."

            while irecovery -m 2>/dev/null | grep -q "DFU Mode"; do
                sleep 1
            done

        fi

        echo "Expecting iPad to be in Recovery Mode shortly, hang in there!"
        sleep 1
    done
    
    echo "Found iPad in Recovery Mode!"
}

turdursra1n_pwn() {
    wait_for_recovery
    usbmuxd_reset

    while ! turdusra1n -ED; do
        echo "Something went wrong. Lets try that again..."
        sleep 1
    done
}

retry_pwn() {
    echo "Something went wrong, lets try that again."
    turdursra1n_pwn
}

start_rd() {
    # Enfore Recovery Mode.
    enter_recovery
    ssh_connected=0

    while [[ $ssh_connected != 1 ]]; do
        # Incase this failed previously and is running again, wait.
        wait_for_recovery
        # Stay in Recovery Mode, prevent normal mode booting until ramdisk boots and runs script to restore this. Unless we enter DFU mode accidentally this is the most useful case of enforce_recovery ever.
        enforce_recovery
        # Clear any existing iproxy...
        iproxy_kill
        # Attempt to boot ramdisk...
        (cd bin/Legacy-iOS-Kit && ./restore.sh --no-version-check --no-internet-check --sshrd-boot-rd-only)
        # Restart after ramdisk script kills our usbmuxd.
        usbmuxd_reset   
        # Start our own proxy for USB SSH fresh...
        iproxy_kill
        iproxy_start
        echo "Waiting 5 seconds before testing SSH ramdisk connection, please standby..."
        sleep 5
        # SSH connection check.
        ssh_connected=$(sshpass -p 'alpine' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 6414 root@127.0.0.1 'echo 1' 2>/dev/null)
    done

    # Need to reset this for ramdisk round 2.
    ssh_connected=0

    echo "Booted SSH Ramdisk!"

    #ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 6414 root@127.0.0.1
}

wait_for_activation()
{
    # This confirms the iPad is activated. It does not confirm if iCloud was signed in, if Find My iPad was turned off, or if an active cell service SIM was used during activation.
    while ! is_activated; do
        read -p "iPad is not activated! Please make sure all of the above criteria are true as well and then press enter."
        sleep 1
    done
}

got_all_activation_files() {
    if [[ -f data/$device-$serial/activate/activation_records.tar.gz && \
          -f data/$device-$serial/activate/data_ark.plist.tar.gz && \
          -f data/$device-$serial/activate/IC-Info.sisv.tar.gz && \
          -f data/$device-$serial/activate/com.apple.commcenter.device_specific_nobackup.plist.tar.gz && \
          -f data/$device-$serial/activate/com.apple.factorydata.tar.gz ]]; then
        return 0
    else
        return 1
    fi
}

get_activation() {
    # Need to get activation files.
    echo -e "Existing activation files not backed up yet.\nObtaining activation files..."
    # Hail Mary if on latest iOS 16 already.
    ios_version=$(ideviceinfo 2>/dev/null | grep "ProductVersion" | awk '{print $2}')

    # Set $not_normal when first connecting/detecting iPad if it is in Recovery or DFU Mode.
    if [ "$not_normal" == "true" ]; then
        echo "Your iPad is not in normal mode, so iOS version can not be determined. Restoring iPad to iOS 16.7.12."
        restore_ios_15=true
    elif [ "$ios_version" != "16.7.12" ]; then
        echo "Latest iOS version is not installed. Restoring iPad to iOS 16.7.12."
        restore_ios_15=true
    elif [ "$ios_version" == "16.7.12" ]; then
        did_you_follow_instructions
    fi

    if [ "$restore_ios_16" == "true" ]; then
        restore_ios_16_for_device
    fi

    # Makes sure we don't stop until we actually get the activation files.
    while ! got_all_activation_files; do
        # Send it...
        start_rd

        expect <<EOF
        # Mount.
        spawn ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 6414 root@127.0.0.1
        expect {
            "continue connecting" {
                send "yes\r"
                exp_continue
            }
            "password:" {
                send "alpine\r"
            }
        }

        expect "#"
        send "mount_filesystems\r"
        expect "#"
        
        # Ramdisk allows RW of / on unjailbroken iOS 16.7.12. on /private/var we have stable RO. RW sometimes doesn't work, so use / as scratch dir.
        send "mkdir /mnt1/activate\r"
        expect "#"
        
        # Copy activation_records.
        send "cp -a /mnt2/containers/Data/System/*/Library/activation_records /mnt1/activate/activation_records\r"
        expect "#"

        # Copy data_ark.plist.
        send "cp -a /mnt2/containers/Data/System/*/Library/activation_records/../internal/data_ark.plist /mnt1/activate\r"
        expect "#"

        # Copy IC-Info.sisv for notifications/ft/imessage/etc
        send "cp -a /mnt2/mobile/Library/FairPlay/iTunes_Control/iTunes/IC-Info.sisv /mnt1/activate\r"
        expect "#"

        # Copy com.apple.commcenter.device_specific_nobackup.plist
        send "cp -a /mnt2/wireless/Library/Preferences/com.apple.commcenter.device_specific_nobackup.plist /mnt1/activate\r"
        expect "#"
        
        # Copy com.apple.factorydata
        send "cp -a /mnt1/System/Library/Caches/com.apple.factorydata /mnt1/activate/com.apple.factorydata\r"
        expect "#"

        # Create tars.
        send "cd /mnt1/activate\r"
        expect "#"
        
        # activation_records.
        send "tar zcf activation_records.tar.gz activation_records\r"
        expect "#"

        # data_ark.plist.
        send "tar zcf data_ark.plist.tar.gz data_ark.plist\r"
        expect "#"
        send "rm data_ark.plist\r"
        expect "#"
        
        # IC-Info.sisv. 
        # Silence error: "tar: copyfile pack (IC-Info.sisv) failed: No such file or directory" because we still get the file fine.
        send "tar zcf IC-Info.sisv.tar.gz IC-Info.sisv > /dev/null 2>&1\r"
        expect "#"
        send "rm IC-Info.sisv\r"
        expect "#"

        # com.apple.commcenter.device_specific_nobackup.plist.
        send "tar zcf com.apple.commcenter.device_specific_nobackup.plist.tar.gz com.apple.commcenter.device_specific_nobackup.plist\r"
        expect "#"
        send "rm com.apple.commcenter.device_specific_nobackup.plist\r"
        expect "#"

        # com.apple.factorydata.
        send "tar zcf com.apple.factorydata.tar.gz com.apple.factorydata\r"
        expect "#"

        # Delete all directories.
        send "rm -rf */\r"
        expect "#"

        send "exit\r"

        # Transfer tars to computer.
        spawn scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r -P 6414 root@127.0.0.1:/mnt1/activate data/$device-$serial
        expect {
            "continue connecting" {
                send "yes\r"
                exp_continue
            }
            "password:" {
                send "alpine\r"
            }
        }
        expect eof  

        # Unmount and Reboot.
        spawn ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 6414 root@127.0.0.1
        expect {
            "continue connecting" {
                send "yes\r"
                exp_continue
            }
            "password:" {
                send "alpine\r"
            }
        }

        expect "#"
        send "reboot\r"
        expect "closed by remote host."
        expect eof
EOF

        iproxy_kill

        # Check to see if user follows instructions.  If not when we get back to restore_ipsw() it will prompt to go through get_activation() again.
        if ! got_all_activation_files; then
            echo "Error: not all activation files were backed up. Please make sure you complete all steps before activation files are backed up. A999 Activator will try getting activation files again."
            read -p "Press any key to continue..."
        fi
    done
}

restore_ipsw() {
    # If we are using this to restore to iOS 15, don't get stuck in an infinite loop.
    if [ "$restore_ios_16" == "false" ]; then
        while ! got_all_activation_files; do
            get_activation
        done
    fi
    
    enter_recovery
    enforce_recovery

    # Check that we have ipsw file.
    file="$(basename $1)"

    if [ ! -f data/ipsw/$file ]; then
        echo "Downloading $file..."
        
        while ! curl -L $1 -o data/ipsw/$file; do
            echo "Download failed, trying again."
            rm $file
        done
    fi

    # Get ver and build number, i.e. 9.2_13D20 for possible iPad Pro downgrade (even though we can't use 13D20 or any 'new' iOS 9.2.1 for other devices because jbme does not work)... Build number is important for iPad Pro and iPad Pro 12.9" which have 2 different iOS 9.2.1 versions available for restore.
    ver=$(echo "$file" | sed -E 's/.*_([0-9]+\.[0-9]+(\.[0-9]+)?)_([0-9A-Z]+)_Restore\.ipsw/\1_\3/')

    echo "Restoring iOS $ver with $file.."

    mkdir -p data/$device-$serial/$ver 

    #SHCblock.
    # BUG (in turdus_merula since v1.1). This can exit ok but it really didn't get the PTE block so we need to check again even after it returns 0. This is done for SHCBlock just in case the same could happen (trust issues since PTEBlock surfaced).
    while ! find data/$device-$serial/$ver/block -type f -name "*-shcblock2.bin" 2>/dev/null | grep -q . 2>/dev/null; do
        echo "Getting SHCBlock..."
        turdursra1n_pwn

        while ! echo 1 | turdus_merula -C data/$device-$serial/$ver --get-shcblock data/ipsw/$file; do
            retry_pwn
        done

        wait_for_recovery
        enforce_recovery
    done

    # PTEblock.
    # BUG (in turdus_merula since v1.1). This can exit ok but it really didn't get the PTE block so we need to check again even after it returns 0.
    while ! find data/$device-$serial/$ver/block -type f -name "*-pteblock2.bin" 2>/dev/null | grep -q . 2>/dev/null; do
        echo "Getting PTEBlock..."
        turdursra1n_pwn

        while ! echo 1 | turdus_merula -C data/$device-$serial/$ver --get-pteblock --load-shcblock data/$device-$serial/$ver/block/*-shcblock2.bin data/ipsw/$file; do
            retry_pwn
        done

        wait_for_recovery
        enforce_recovery
    done

    echo "Restoring..."
    # Restore.
    turdursra1n_pwn
    usbmuxd_reset

    while ! echo 1 | turdus_merula -C data/$device-$serial/$ver -o --load-pteblock data/$device-$serial/$ver/block/*-pteblock2.bin data/ipsw/$file; do
        retry_pwn
    done
}

downgrade() {
    # We need to do this to prevent an issue where the device can crash randomly and enter DFU mode on the final restored firmware lower then 10.2.1. This also fixes a weird issue when you restore 9.3.x after being on 9.3.x, it can sometimes grey out the Wi-Fi. This was originally 10.2.1, but due to an issue with restoring/booting the ramdisk this now is 10.2.1 (which is HFS+) https://www.reddit.com/r/LegacyJailbreak/comments/1nj598d/issue_downgrading_a9_devices_to_ios_9x_using/.
    # When we end the activation get ramdisk we ALWAYS will be in Recovery Mode.
    if [ $device == "iPad-Pro-12.9"" ]; then
        restore_ipsw http://appldnld.apple.com/ios10.2.1/031-96800-20170112-6151CD56-D81D-11E6-A447-F501D55B5B9D/iPad_5.5_10.2.1_14D27_Restore.ipsw
    elif [ $device == "iPad-Pro" ]; then
        restore_ipsw http://appldnld.apple.com/ios10.2.1/031-96803-20170112-6151BFBE-D81D-11E6-8553-F701D55B5B9D/iPad_4.7_10.2.1_14D27_Restore.ipsw
    elif [ $device == "iPad-se" ]; then
        restore_ipsw http://appldnld.apple.com/ios10.2.1/031-96769-20170112-61558B4E-D81D-11E6-9610-F301D55B5B9D/iPadSE_10.2.1_14D27_Restore.ipsw
    fi

    restore_ipsw $1
    start_rd

    expect <<EOF
    # Set up /.
    spawn ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 6414 root@127.0.0.1
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
        }
    }

    expect "#"
    send "mount_hfs /dev/disk0s1s1 /mnt1\r"
    expect "#"
    send "mount_hfs /dev/disk0s1s2 /mnt2\r"
    expect "#"
    send "rm -rf /mnt1/activation\r"
    expect "#"
    send "mkdir /mnt1/Library/LaunchDaemons\r"
    expect "#"
    send "exit\r"

    # Transfer activation tars to phone.
    spawn scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r -P 6414 data/$device-$serial/activate root@127.0.0.1:/mnt1
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
        }
    }
    expect eof

    # Transfer launch daemon com.alex.activate.plist to host.
    spawn scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 6414 payload/com.alex.activate.plist root@127.0.0.1:/mnt1/Library/LaunchDaemons
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
        }
    }
    expect eof

    # Transfer activate script to host.
    spawn scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 6414 payload/activate root@127.0.0.1:/mnt1/usr/bin
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
        }
    }
    expect eof

    # Transfer freeze.tar to host.
    spawn scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 6414 bin/Legacy-iOS-Kit/resources/jailbreak/freeze.tar root@127.0.0.1:/mnt1
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
        }
    }
    expect eof

    # Transfer launchctl.tar to host.
    spawn scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 6414 bin/Legacy-iOS-Kit/resources/jailbreak/launchctl.tar root@127.0.0.1:/mnt1
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
        }
    }
    expect eof

    # Transfer io.pangu93.loader.plist to host.
    spawn scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 6414 bin/Legacy-iOS-Kit/resources/jailbreak/io.pangu93.loader.plist root@127.0.0.1:/mnt1/Library/LaunchDaemons
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
        }
    }
    expect eof

    # Transfer plutil (from com.bingner.plutil_0.2.1_iPados-arm.deb) to host.
    spawn scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 6414 payload/plutil root@127.0.0.1:/mnt1/usr/bin/plutil
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
        }
    }
    expect eof

    spawn ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 6414 root@127.0.0.1
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
        }
    }

    expect "#"

    # Set permissions for activate.
    send "chmod 755 /mnt1/usr/bin/activate\r"
    expect "#"
    send "chown root:wheel /mnt1/usr/bin/activate\r"
    expect "#"

    # Set permissions for plutil.
    send "chmod 755 /mnt1/usr/bin/plutil\r"
    expect "#"
    send "chown root:wheel /mnt1/usr/bin/plutil\r"
    expect "#"

    # Install chflags from ramdisk
    send "cp -a /usr/bin/chflags /mnt1/usr/bin/chflags\r"
    expect "#"

    # Set permissions for launch daemon com.alex.activate.plist.
    expect "#"
    send "chmod 644 /mnt1/Library/LaunchDaemons/com.alex.activate.plist\r"
    expect "#"
    send "chown root:wheel /mnt1/Library/LaunchDaemons/com.alex.activate.plist\r"
    expect "#"
    
    # Move Setup.app to prevent possible deactivation causing it to trigger.
    send "mv /mnt1/Applications/Setup.app /mnt1/Applications/Setup.bak\r"
    expect "#"
    
    # BEGIN JAILBREAK BOOTSTRAP INSTALLATION.
    # Set permissions for launch daemon io.pangu93.loader.plist.
    send "chmod 644 /mnt1/Library/LaunchDaemons/io.pangu93.loader.plist \r"
    expect "#"
    send "chown root:wheel /mnt1/Library/LaunchDaemons/io.pangu93.loader.plist\r"
    expect "#"

    send "cd /mnt1\r"
    expect "#"

    # Extract freeze.tar.
    send "tar -xf freeze.tar -C .\r"
    expect "#"
    send "rm freeze.tar\r"
    expect "#"

    # Extract launchctl.tar.
    send "tar -xf launchctl.tar -C .\r"
    expect "#"
    send "rm launchctl.tar\r"
    expect "#"

    # Is this the symlink trick to write to /var?) 
    send "mv private/var/lib private\r"
    expect "#"
    send "mv private/var/mobile/Library/Preferences/com.apple.springboard.plist private\r"
    expect "#"
    send "rm -r private/var/*\r"
    expect "#"
    send "touch .cydia_no_stash\r"
    expect "#"
    send "cd /mnt2\r"
    expect "#"
    send "ln -s /private/lib\r"
    expect "#"
    send "cd mobile/Library/Preferences\r"
    expect "#"
    send "rm -f com.apple.springboard.plist\r"
    expect "#"
    send "ln -s /private/com.apple.springboard.plist\r"
    expect "#"
    send "chown 501:501 com.apple.springboard.plist\r"
    expect "#"
    send "exit\r"

    # Unmount and Reboot. Spawn a new session because symlink trick is weird and prevents unmounting /mnt2.
    spawn ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 6414 root@127.0.0.1
    expect {
        "continue connecting" {
            send "yes\r"
            exp_continue
        }
        "password:" {
            send "alpine\r"
        }
    }

    expect "#"
    send "umount /mnt1\r"
    expect "#"
    send "umount /mnt2\r"
    expect "#"
    send "reboot\r"
    expect "closed by remote host."
    expect eof
EOF

    iproxy_kill
    boot_turdusra1n
    pair_iPad
    echo "Your iPad is now jailbroken! You need to enable it now by visiting http://jbme.ddw.nu/ in Safari after signing in to your WiFi. Once the jailbreak is enabled, your iPad will automatically reboot into Recovery Mode after restoring activation. Do not sign in to iCloud just yet! a999activator is going to start checking for Recovery Mode in 30 seconds so that the LAST STEP can be completed!"
    sleep 30
    boot_turdusra1n

    if ! is_activated; then
        echo "Error: activation was not restored. Please try again."
        exit 1
    fi

    if [ $device == "iPad-Pro-12.9"" ]; then
        boot_script=bootProp-$ver-$serial
    elif [ $device == "iPad-Pro" ]; then      
        boot_script=bootPro-$ver-$serial
    elif [ $device == "iPad-se" ]; then
        boot_script=bootse-$ver-$serial
    fi

    # Delete any existing boot* scripts for this serial number.
    rm -f *-$serial
    
    # Generate boot* script
    echo -e '#!/bin/bash

os="$(uname)"
arch="$(uname -m)"

# OS/arch detection.
# Add all the self-contained binaries we need to the $PATH used within this script.
real_portable_folder="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ "$os" = "Linux" ]; then
    
    if [ "$arch" = "x86_64" ]; then
        PATH="${PATH:+$PATH:}$real_portable_folder/bin/Legacy-iOS-Kit/bin/linux/x86_64:$real_portable_folder/bin/turdus_m3rula_1.1_b0ea3ee7_linux-amd64/bin"
    elif [ "$arch" = "arm64" ]; then
        PATH="${PATH:+$PATH:}$real_portable_folder/bin/Legacy-iOS-Kit/bin/linux/arm64:$real_portable_folder/bin/turdus_m3rula_1.1_b0ea3ee7_linux-arm64/bin"
    else
        echo "Error: Linux on $arch is not supported."
        exit 1
    fi

    echo "Detected Linux on $arch."

elif [ "$os" == "Darwin" ]; then
    PATH="${PATH:+$PATH:}$real_portable_folder/bin/Legacy-iOS-Kit/bin/macos:$real_portable_folder/bin/turdus_m3rula_1.1_b0ea3ee7_macos/bin"
    echo "Detected Mac OS on $arch."
else
    echo "Error: $os is not supported."
    exit 1
fi

echo "PATH: $PATH"
cd "$real_portable_folder"

usbmuxd_reset() {
    if [ "$os" = "Linux" ]; then
        systemctl stop usbmuxd > /dev/null 2>&1
        # If usbmuxd is still running kill it forcibly.
        killall -9 usbmuxd > /dev/null 2>&1
        usbmuxd -f -p > /dev/null 2>&1 &
    fi
}

if [ "$os" = "Linux" ]; then

    if [ "$EUID" -ne 0 ]; then
        echo "Error: root privileges are required to boot your iPad. Please execute $0 with sudo or as root to continue." >&2
        exit 1
    fi

    usbmuxd_reset
fi

# When this script exits, automatically restart usbmuxd as normal. We are root at this point that this takes effect (on Linux).
cleanup() 
{
    if [ "$os" = "Linux" ]; then 
        usbmuxd_reset
    fi
}
trap cleanup EXIT

# Can not trust return values of turdusra1n because at least my 256GB TSMC Pro 12.9" reboots to recovery very occasionally. This has never happened on my 32GB TSMC Pro 12.9".
while irecovery -m 2>/dev/null | grep -q "Recovery Mode"; do
    usbmuxd_reset
    echo "If you get an error about failed to open handle (no device) after Checkmate?, disconnect then reconnect your iPad."

    while ! turdusra1n -TP data/'$device'-'$serial'/'$ver'/block/*-pteblock2.bin; do 
        usbmuxd_reset
        echo "Something went wrong, lets try that again..."
    done

    echo "Please wait, checking for proper booting in 20 seconds"
    sleep 20
done

echo "Enable the jailbreak with http://jbme.ddw.nu in Safari!"

' > $boot_script

    chmod 755 $boot_script
    # Clips the last character otherwise in the echo below.
    boot_script=$(echo "$boot_script" | tr -d '\r')
    echo "Activation was restored! You need to enable the jailbreak with http://jbme.ddw.nu in Safari everytime you boot, but your done! If your phone is powered off or rebooted, it will first boot to Recovery Mode. You'll need to run the $boot_script command (now found in the same folder as the a999 command) to boot it into normal mode."

    case "$ver" in
        9.2*)
            echo "IMPORTANT INFORMATION FOR iOS 9.2 AND iOS 9.2.1 USERS (WHICH YOU ARE): DO NOT SIGN IN TO ICLOUD IN SETUP.APP! It will not work. Instead, complete Setup.app without signing in and get to the home screen. Then, sign in to iCloud with the Settings app!"
            ;;
        9.3*)
            echo "IMPORTANT INFORMATION FOR iOS 9.3, iOS 9.3.1, iOS 9.3.2, AND iOS 9.3.3 USERS (WHICH YOU ARE): iMessage and FaceTime do not work yet!"
            if [ $device != "iPad-se" ]; then
                echo "If you need iMessage and or FaceTime downgrade to iOS 9.2 or iOS 9.2.1 instead."
            fi
            ;;
    esac
}

iPad_Pro_firmware_select() {
    PS3="Select iOS version to downgrade to: "
    options=(
        "9.2 (13C75) (12/8/2015)"
        "9.2.1 (13D15) (1/19/2016)"
        #"9.2.1 (13D20) (2/18/2016)" Can't use because jbme doesn't support it
        "9.3 (13E234) (3/21/2016)"
        "9.3.1 (13E238) (3/31/2016)"
        "9.3.2 (13F69) (5/16/2016)"
        "9.3.3 (13G34) (7/18/2016)"
        "Exit"
    )

    select opt in "${options[@]}"
    do
        case $opt in
            "9.2 (13C75) (12/8/2015)")
                downgrade "http://appldnld.apple.com/ios9.2/031-29140-20151203-674A1328-8D8A-11E5-BD43-55618B8BECEB/iPad6,7_9.2_13C75_Restore.ipsw"
                break;
                ;;
            "9.2.1 (13D15) (1/19/2016)")
                downgrade "http://appldnld.apple.com/ios9.2.1/031-47563-20160119-8C3DDEA8-B968-11E5-918A-CB4A8FD31F8F/iPad6,7_9.2.1_13D15_Restore.ipsw"
                break;
                ;;
            #"9.2.1 (13D20) (2/18/2016)") Can't use because jbme doesn't support it
                #downgrade "http://appldnld.apple.com/ios9.2.1/031-48671-20160217-4BB46F46-D44D-11E5-8BAB-0052919DCAD8/iPad6,7_9.2.1_13D20_Restore.ipsw"
                #break;
                #;;
            "9.3 (13E234) (3/21/2016)")
                downgrade "http://appldnld.apple.com/iOS9.3/031-28362-20160321-5101CF90-EAA8-11E5-951B-CC79BD379832/iPad6,7_9.3_13E233_Restore.ipsw"
                break;
                ;;
            "9.3.1 (13E238) (3/31/2016)")
                downgrade "http://appldnld.apple.com/iOS9.3.1/031-54964-20160331-099887E0-F5E6-11E5-8F56-1FCB2D794EB1/iPad6,7_9.3.1_13E238_Restore.ipsw"
                break;
                ;;
            "9.3.2 (13F69) (5/16/2016)")
                downgrade "http://appldnld.apple.com/ios9.3.2/031-62618-20160516-D6E79C64-13A9-11E6-9BD6-45DA400DF7EB/iPad6,7_9.3.2_13F69_Restore.ipsw"
                break;
                ;;
            "9.3.3 (13G34) (7/18/2016)")
                downgrade "http://appldnld.apple.com/iOS9.3.3/031-60723-20160718-55B463EE-4378-11E6-9EA0-C4FB59E0E9B6/iPad6,7_9.3.3_13G34_Restore.ipsw"
                break;
                ;;
            "Exit")
                break
                ;;
            *)
                echo "Invalid option"
                ;;
        esac
    done
}


iPad_Pro_12.9"_firmware_select() {

    PS3="Select iOS version to downgrade to: "
    options=(
        "9.2 (13C75) (12/8/2015)"
        "9.2.1 (13D15) (1/19/2016)"
        #"9.2.1 (13D20) (2/18/2016)" can't use because jbme doesn't support it
        "9.3 (13E234) (3/21/2016)"
        "9.3.1 (13E238) (3/31/2016)"
        "9.3.2 (13F69) (5/16/2016)"
        "9.3.3 (13G34) (7/18/2016)"
        "Exit"
    )

    select opt in "${options[@]}"
    do
        case $opt in
            "9.2 (13C75) (12/8/2015)")
                downgrade "http://appldnld.apple.com/ios9.2/031-29216-20151203-674A518A-8D8A-11E5-97B3-57618B8BECEB/iPad6,8_9.2_13C75_Restore.ipsw"
                break;
                ;;
            "9.2.1 (13D15) (1/19/2016)")
                downgrade "http://appldnld.apple.com/ios9.2.1/031-47548-20160119-8C3DB6D0-B968-11E5-AD30-CD4A8FD31F8F/iPad6,8_9.2.1_13D15_Restore.ipsw"
                break;
                ;;
            #"9.2.1 (13D20) (2/18/2016)") can't use because jbme doesn't support it
                #downgrade "http://appldnld.apple.com/ios9.2.1/031-49308-20160217-4BADBB56-D44D-11E5-B486-0152919DCAD8/iPad6,8_9.2.1_13D20_Restore.ipsw"
                #break;
                #;;
            "9.3 (13E234) (3/21/2016)")
                downgrade "http://appldnld.apple.com/iOS9.3/031-28427-20160321-BC5C2406-EAA9-11E5-976F-EB7DBD379832/iPad6,8_9.3_13E233_Restore.ipsw"
                break;
                ;;
            "9.3.1 (13E238) (3/31/2016)")
                downgrade "http://appldnld.apple.com/iOS9.3.1/031-55357-20160331-09B68CEA-F5E6-11E5-B924-2BCB2D794EB1/iPad6,8_9.3.1_13E238_Restore.ipsw"
                break;
                ;;
            "9.3.2 (13F69) (5/16/2016)")
                downgrade "http://appldnld.apple.com/ios9.3.2/031-62062-20160516-6A1A9458-13A7-11E6-8779-B8D6400DF7EB/iPad6,8_9.3.2_13F69_Restore.ipsw"
                break;
                ;;
            "9.3.3 (13G34) (7/18/2016)")
                downgrade "http://appldnld.apple.com/iOS9.3.3/031-60339-20160718-06EB8404-4378-11E6-A195-9DF759E0E9B6/iPad6,8_9.3.3_13G34_Restore.ipsw"
                break;
                ;;
            "Exit")
                break
                ;;
            *)
                echo "Invalid option"
                ;;
        esac
    done
}

iPad_se_firmware_select() {

    PS3="Select iOS version to downgrade to: "
    options=(
        "9.3 (13E232) (3/21/2016)"
        "9.3.1 (13E238) (3/31/2016)"
        "9.3.2 (13F69) (5/16/2016)"
        "9.3.3 (13G34) (7/18/2016)"
        "Exit"
    )

    select opt in "${options[@]}"
    do
        case $opt in
            "9.3 (13E233) (3/21/2016)")
                downgrade "http://appldnld.apple.com/iOS9.3/031-20813-20160321-50FF2B1E-EAA8-11E5-A40C-C179BD379832/iPad6,3_9.3_13E234_Restore.ipsw"
                break;
                ;;
            "9.3.1 (13E238) (3/31/2016)")
                downgrade "http://appldnld.apple.com/iOS9.3.1/031-54866-20160331-09994CCA-F5E6-11E5-8354-1DCB2D794EB1/iPad6,3_9.3.1_13E238_Restore.ipsw"
                break;
                ;;
            "9.3.2 (13F69) (5/16/2016)")
                downgrade "http://appldnld.apple.com/ios9.3.2/031-62643-20160516-F67BDAE0-13A9-11E6-A5A3-AEDA400DF7EB/iPad6,3_9.3.2_13F69_Restore.ipsw"
                break;
                ;;
            "9.3.2 (13F72) (6/2/2016)")
                downgrade "http://appldnld.apple.com/ios9.3.2/031-63513-20160531-52E11156-2665-11E6-8860-F0F5662719FC/iPad6,3_9.3.2_13F72_Restore.ipsw"
                break;
                ;;
            "9.3.3 (13G34) (7/18/2016)")
                downgrade "http://appldnld.apple.com/iOS9.3.3/031-60435-20160718-06EB0394-4378-11E6-AB0E-9FF759E0E9B6/iPad6,3_9.3.3_13G34_Restore.ipsw"
                break;
                ;;
            "Exit")
                break
                ;;
            *)
                echo "Invalid option"
                ;;
        esac
    done
}

# Begin actual execution. 

if [ "$os" = "Linux" ]; then

    # On Linux we need root.
    if [ "$EUID" -ne 0 ]; then
        echo "Error: a999 must be ran with root privileges on Linux. Please execute it with sudo or as the root user to continue."
        exit 1
    fi

elif [ "$os" = "Darwin" ]; then
    # All these executables are signed so that is the only think preventing gatekeeper from allowing the script to be automatic is the quarintine attributes.
    # Remove any quarintine attributes in this folder.
    xattr -rc .
else
    echo "Error: unsupported operating system!"
    exit 1
fi

# When this script exits, automatically restart usbmuxd as normal. We are root at this point that this takes effect (on Linux).
cleanup() 
{
    if [ "$os" = "Linux" ]; then 
        usbmuxd_reset
    fi
}
trap cleanup EXIT

# Check for the existence of the binary launch daemon which is generated for the release by the build script.
if [ ! -f "payload/com.alex.activate.plist" ]; then
    echo "Error: can not find payload/com.alex.activate.plist. This most likely means you are trying to execute a999 from the source tree, rather then a release which is not allowed. Please execute the build command in the source tree and cd into the built release. If you downloaded an a999activator release and are getting this error, you release is incomplete and missing a neccesary file. Please redownload the release and run a999activator again."
    exit 1
fi

# Update functionallity. We need to get 2 things, the data folder and any boot* scripts.

if [ "$1" == "-u" ]; then

    if [ "$#" -ne 2 ]; then
        echo "You gave the -u argument, which expect an existing a999activator release directory as the following argument."
        exit 1
    fi

    if [ -d "$2"/data ]; then
        echo "Found existing data folder!"
        cp -rv "$2"/data .
        echo "Copied existing data folder to a999activator!"
    else
        echo "Error: Could not find the data folder in $2!"
        exit 1
    fi

    # Don't print error messages if no boot-* files exist.
    cp -rv "$2"/boot-* . 2>/dev/null 
    exit 0
fi

if [ ! -d data ]; then
    echo "Creating data folder..."
else
    echo "Loaded existing data folder!"
fi

# Create ipsw directory if it does not exist.
mkdir -p data/ipsw

if [ ! -f "bin/Legacy-iOS-Kit/resources/firstrun" ]; then
    echo "Installing dependencies..."

    (cd bin/Legacy-iOS-Kit && ./restore.sh --no-version-check --no-internet-check)
    # This is to account for LibUSB being just installed.

    echo -e "Please do the following to ensure A999 Activator can talk to your iPad:\n\n* Disconnect your USB-A Lightning cable from your mac.\n* Connect the USB-A Lightning cable to the Mac wih your iPad connected.\n"

    read -p "After doing the above, press any key to continue..."
fi

# Fresh USB connection.
usbmuxd_reset

echo "Searching for an iPad Pro 9.7", iPad Pro 12.9" connected to this computer with a USB-A Lightning cable. Please wait..."

# Need the serial number to identify what cached data to use. This is available in Recovery Mode and Normal mode, but not in DFU Mode so we don't allow this to run until we get into Recovery Mode if DFU Mode is detected.
echo "Checking for iPad in DFU Mode..."

if irecovery -m 2>/dev/null | grep -q "DFU Mode"; then
    wait_for_recovery
fi

# Loop until the iPad can be detected in Recovery Mode or Normal Mode. It sure as hell aint in DFU Mode at this point...
while true; do

    echo "Checking for iPad in Recovery Mode..."

    if irecovery -m 2>/dev/null | grep -q "Recovery Mode"; then
        echo "Info: iPad was found in Recovery Mode."
        not_normal=true
        serial=$(irecovery -q 2>/dev/null | grep -i 'SRNM:' | awk '{print $2}')

        if irecovery -q 2>/dev/null |  grep '^PRODUCT: iPad8,2'; then
            echo "iPad Pro 12.9" detected!"
            device=iPad-Pro-12.9"
        elif irecovery -q 2>/dev/null | grep -q '^PRODUCT: iPad8,1'; then
            echo "iPad Pro 9.7" detected!"
            device=iPad-Pro-9.7"
        else
            echo "Error: Currently only iPad Pro 9.7", iPad Pro 12.9" are supported! If you have a supported device, make sure it is connected with a Lightning to USB-A cable to this computer"
            exit 1
        fi

        if irecovery -q 2>/dev/null | grep -q '^CPID: 0x8003'; then
            echo "Info: TSMC A9 chip detected!"
            break
        elif irecovery -q 2>/dev/null | grep -q '^CPID: 0x8001'; then
            echo "Info: Samsung A9X chip detected! You must have an iPad Pro!"
            break
        elif irecovery -q 2>/dev/null | grep -q '^CPID: 0x8000'; then
            echo "Info: Samsung A9 chip detected!"
            break
        fi

    else
        # Gets here if no iPad is connected as well so set special arg.
        echo "Checking for iPad in Normal Mode..."
        pair_iPad first_time
    
        serial=$(ideviceinfo 2>/dev/null | grep -i '^SerialNumber:' | awk '{print $2}')
        
        if ideviceinfo 2>/dev/null | grep -q '^ProductType: iPad6,7' > /dev/null 2>&1; then
            echo "iPad Pro 12.9" (WiFi) detected!"
            device=iPad-Pro-12.9-wifi
        elif ideviceinfo 2>/dev/null | grep -q '^ProductType: iPad6,8' > /dev/null 2>&1; then
            echo "iPad Pro 12.9" (Cellular)!"
            device=iPad-Pro
        elif ideviceinfo 2>/dev/null | grep -q '^ProductType: iPad8,4' > /dev/null 2>&1; then
            echo "iPad SE detected!"
            device=iPad-se
        else
            echo "Error: currently only iPad Pro 9.7", iPad Pro 12.9" are supported! If you have a supported iPad, make sure it is connected with a Lightning to USB-A cable to this computer and try again."
            exit 1
        fi

        if ideviceinfo 2>/dev/null |  grep -q '^HardwarePlatform: s8003'; then
            echo "Info: TSMC A9 chip detected!"
            break
        elif ideviceinfo 2>/dev/null |  grep -q '^HardwarePlatform: s8001'; then
            echo "Info: Samsung A9X chip detected! You must have an iPad Pro!"
            break
        elif ideviceinfo 2>/dev/null |  grep -q '^HardwarePlatform: s8000'; then
            echo "Info: Samsung A9 chip detected!"
            break
        fi
    fi
done

echo "Serial Number Identifier: $serial"

if [ $device == "iPad-Pro-12.9" ]; then
    iPad_Pro_12.9_firmware_select
elif [ $device == "iPad-Pro-9.7" ]; then
    iPad_Pro_9.7_firmware_select
fi
