#!/bin/bash

# EzRe build script for A999XActivator.
version="1.0"
program=a999
release_name=a999x-activator-v$version
set -e

cd "$(dirname "$0")"

sudo rm -rf $release_name $release_name.zip

if [ "$1" == "clean" ]; then
    exit 0
fi

mkdir $release_name

if sed --version >/dev/null 2>&1; then
    echo "Info: using GNU sed"
    bsd_sed=false
else
    echo "Info: using BSD sed"
    bsd_sed=true
fi

if [ "$bsd_sed" == "true" ]; then
    sed -i '' -E "s|^version=.*|version=$version|" $program
else
    sed -i'' -E "s|^version=.*|version=$version|" $program
fi

release_files="$program *.md bin payload"
cp -r ${release_files} $release_name

# Convert from xml to binary like other iOS 9 launch daemons.
os="$(uname)"

if [[ "$os" == "Linux" ]]; then

    if ! command -v plistutil &>/dev/null; then
        echo "Info: root privilages are required to install plistutil:"

        if command -v apt &>/dev/null; then
            sudo apt install -y libplist-utils
        elif command -v dnf &>/dev/null; then
            sudo dnf install -y libplist
        elif command -v pacman &>/dev/null; then
            sudo pacman -Sy --noconfirm libplist
        else
            echo "Error: could not detect your package manager. You must install libplist manually before the build script can continue."
            exit 1
        fi
    fi

    plistutil -f bin -i com.alex.activate.plist.xml -o $release_name/payload/com.alex.activate.plist
elif [[ "$os" == "Darwin" ]]; then
    plutil -convert binary1 com.alex.activate.plist.xml -o $release_name/payload/com.alex.activate.plist
fi

chmod -R 777 $release_name
zip -r $release_name.zip $release_name
