#!/bin/bash

# EzRe build script for A999Activator.
version="1.0.4"
program=a999
turdus_merula=turdus_m3rula_1.1_b0ea3ee7_macos
release_name=a999-activator-v$version-mac-os-universal

cd "$(dirname "$0")"

rm -rf $release_name $release_name.zip

if [ "$1" == "clean" ]; then
    exit 0
fi

mkdir $release_name

if sed --version >/dev/null 2>&1; then
    echo "Info: using GNU sed"
    bsd_sed=false
else
    echo "Info: using BSD sed"
    bsd_sed=true
fi

if [ "$bsd_sed" == "true" ]; then
    sed -i '' -E "s|^version=.*|version=$version|" $program
    sed -i '' -E "s|^turdus_merula=.*|turdus_merula=$turdus_merula|" $program
else
    sed -i'' -E "s|^version=.*|version=$version|" $program
    sed -i'' -E "s|^turdus_merula=.*|turdus_merula=$turdus_merula|" $program
fi

release_files="$program *.md $turdus_merula Legacy-iOS-Kit plutil activate"
# Convert from xml to binary like other iOS 9 launch daemons.
plutil -convert binary1 com.alex.activate.plist.xml -o "$release_name"/com.alex.activate.plist
cp -r ${release_files} "$release_name"
touch "$release_name"/.firstrun
chmod -R 777 $release_name
zip -r $release_name.zip $release_name

